name: Hello, everyone!
description: Greet and record the time
author: dan

inputs:
  who-to-greet: 
    default: World

outputs:
  time:
    description: test

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.who-to-greet }}
