name: Github Actions docker ci

on: 
  push:
    branches: main
    paths-ignore: .github/**

  pull_request:
    branches: main

  schedule:
    - cron: '15 6 * * 0'

  workflow_dispatch:
    inputs:
      env:
        type: environment
        
    
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo ${{ github.event_name }};
            echo ${{ github.ref }};

      - uses: actions/checkout@v4

      - name: Run my own container action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'dan'

  Test:
    runs-on: ubuntu-latest
    environment: Test
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - run: |
            echo Testing

  Load-Test:
    runs-on: ubuntu-latest
    needs: [Test]
    environment: Load-Test
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - run: |
            echo Testing
            sleep 15

  Prod:
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://writeabout.net
    needs: [Test,Load-Test]
    if: ${{ inputs.environment == 'Production' }}
    steps:
      - run: |
            echo step1 deploying
            sleep 15
      - run: |
            echo step2 deploying
            sleep 15
      - run: |
            echo step3 deploying
            sleep 15            
      - run: |
            echo step4 deploying
            sleep 15            
      - run: |
            echo step5 deploying
            sleep 15            
