name: Github Actions docker ci

on: 
  push:
    branches: main
    paths-ignore: .github/**

  pull_request:
    branches: main

  schedule:
    - cron: '15 6 * * 0'

  workflow_dispatch:
    
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo ${{ github.event_name }};
            echo ${{ github.ref }};

      - uses: actions/checkout@v4

      - name: Run my own container action
        uses: ./hello-world-docker-ci
        with:
          who-to-greet: 'dan'
